// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWgLgNL1a9DifsN09fuB2OmawtTS4PFxY',
    appId: '1:829023179082:web:2b9a24db2bc57e2253b1b3',
    messagingSenderId: '829023179082',
    projectId: 'smart-e-kantin-8359d',
    authDomain: 'smart-e-kantin-8359d.firebaseapp.com',
    storageBucket: 'smart-e-kantin-8359d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQqrzNbnr7g6jbMtktGB5w9IppoPKFMS4',
    appId: '1:829023179082:android:72e049ee8d1aac2153b1b3',
    messagingSenderId: '829023179082',
    projectId: 'smart-e-kantin-8359d',
    storageBucket: 'smart-e-kantin-8359d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9U3JcAuKqlWUeU4caK3jOZUhSP7g3uvA',
    appId: '1:829023179082:ios:6fe303d78b0007b653b1b3',
    messagingSenderId: '829023179082',
    projectId: 'smart-e-kantin-8359d',
    storageBucket: 'smart-e-kantin-8359d.firebasestorage.app',
    iosBundleId: 'com.example.smartEkantin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9U3JcAuKqlWUeU4caK3jOZUhSP7g3uvA',
    appId: '1:829023179082:ios:6fe303d78b0007b653b1b3',
    messagingSenderId: '829023179082',
    projectId: 'smart-e-kantin-8359d',
    storageBucket: 'smart-e-kantin-8359d.firebasestorage.app',
    iosBundleId: 'com.example.smartEkantin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWgLgNL1a9DifsN09fuB2OmawtTS4PFxY',
    appId: '1:829023179082:web:4292c324d955b75e53b1b3',
    messagingSenderId: '829023179082',
    projectId: 'smart-e-kantin-8359d',
    authDomain: 'smart-e-kantin-8359d.firebaseapp.com',
    storageBucket: 'smart-e-kantin-8359d.firebasestorage.app',
  );

}